matrix:
  include:
    - os: linux
      arch: arm64
      language: python
      python: '3.6'
      env: PYTHON=/home/travis/virtualenv/python3.6.9/bin
      cache:
        directories:
          - $HOME/.pip-cache/
          - /home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages
      addons:
        apt:
          packages:
            - autogen
            - autoconf
            - automake
            - libtool
            - pkg-config
            - libpcap-dev
            - libusb-1.0-0-dev
            - libdbus-glib-1-dev
            - libbluetooth-dev
            - libnl-genl-3-dev
            - flex
            - bison

    - os: linux
      arch: arm64
      language: python
      python: '3.7'
      env: PYTHON=/home/travis/virtualenv/python3.7.5/bin
      cache:
        directories:
          - $HOME/.pip-cache/
          - /home/travis/virtualenv/python3.7.5/lib/python3.7/site-packages
      addons:
        apt:
          packages:
            - autogen
            - autoconf
            - automake
            - libtool
            - pkg-config
            - libpcap-dev
            - libusb-1.0-0-dev
            - libdbus-glib-1-dev
            - libbluetooth-dev
            - libnl-genl-3-dev
            - flex
            - bison

    - os: linux
      arch: arm64
      language: python
      python: '3.8'
      env: PYTHON=/home/travis/virtualenv/python3.8.0/bin
      cache:
        directories:
          - $HOME/.pip-cache/
          - /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages
      addons:
        apt:
          packages:
            - autogen
            - autoconf
            - automake
            - libtool
            - pkg-config
            - libpcap-dev
            - libusb-1.0-0-dev
            - libdbus-glib-1-dev
            - libbluetooth-dev
            - libnl-genl-3-dev
            - flex
            - bison

install:
  - ls /home/travis/virtualenv/
  - sudo chown -Rv $USER:$GROUP ~/.cache/pip/wheels
  - python3 -m pip install --upgrade pip
  - python3 -m pip install --upgrade setuptools wheel twine codecov
  - python3 -m pip install -r requirements.txt
  - python3 setup.py bdist_wheel
  - ls dist/

script:
  - python3 -m coverage run tests.py

after_success:
  - python3 -m codecov
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ ! -z "$TRAVIS_TAG" ]; then
      python3 -m twine --skip-existing dist/*.whl
    fi
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ -z "$TRAVIS_TAG" ]; then
      python3 -m twine --skip-existing dist/*.whl
    fi