name: build_publish_manylinux_x86_64

on:
  push: # just to debug
    branches:
    - master
  release:
    types: [created]

jobs:
  build_publish_manylinux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install twine

    - name: Build and generate wheels
      uses: RalfG/python-wheels-manylinux-build@v0.4.2-manylinux_2_24_x86_64
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310 pp37-pypy37_pp73 pp38-pypy38_pp73 pp39-pypy39_pp73'
        build-requirements: 'cffi>=1.15.0 psutil>=5.8.0 numpy>=1.19.5 pandas>=1.1.5,<6.3 dpkt>=1.9.7'
        system-packages: 'autoconf automake libtool pkg-config gettext libjson-c-dev libusb-1.0-0-dev libdbus-glib-1-dev libbluetooth-dev libnl-genl-3-dev flex bison python3-pip'
        pre-build-command: 'python3 prepare.py'

    - name: Upload generated wheel
      uses: actions/upload-artifact@v3
      with:
        name: generated_wheel
        path: |
          dist/nfstream-*.whl
        retention-days: 1
