name: build_test_aarch64
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build_test_linux:
    name: ${{ matrix.python-version }} on linux-aarch64
    runs-on: [self-hosted, ARM64]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["python3.9"]

    steps:
    - name: Cleanup build folder
      run: |
        ls -la ./
        sudo rm -rf ./* || true
        sudo rm -rf ./.??* || true
        ls -la ./

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install requirements
      run: |
        ${{ matrix.python-version }} -m pip install --upgrade pip
        ${{ matrix.python-version }} -m pip install -r dev_requirements.txt

    - name: Prepare
      run: |
        ${{ matrix.python-version }} prepare.py

    - name: Build
      run: |
        ${{ matrix.python-version }} -m pip install .

    - name: Test and generate coverage report
      run: |
        ${{ matrix.python-version }} -m pip install coverage
        ${{ matrix.python-version }} -m coverage run -m pytest tests.py
        ${{ matrix.python-version }} -m coverage combine

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
