name: build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  release:
    types: [created]
  schedule:
    # CI run every day (except weekends) at 22.
    - cron:  '0 22 * * 1-5'
    
jobs:
  test:
    name: ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macOS-latest"]
        python-version: [pypy3, 3.8, 3.7, 3.6]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Get pip cache dir
      id: pip-cache
      run: |
        python -m pip install --upgrade pip setuptools wheel
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Pip cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install ubuntu Prerequisites
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get install autoconf automake libtool pkg-config libpcap-dev flex bison
    - name: Installing macOS prerequisites
      if: startsWith(matrix.os, 'macOS')
      run: |
        brew install autoconf automake libtool pkg-config
    - name: Installing package dependencies
      run: |
        pip install wheel twine setuptools codecov
        pip install -r requirements.txt
        python setup.py bdist_wheel
        ls nfstream/
    - name: Generated wheel
      run: |
        ls dist/
    - name: Testing
      run: |
        coverage run tests.py
    - name: Uploading coverage report
      if: success()
      run: |
        codecov -t ${{ secrets.CODECOV_TOKEN }}
    - name: Publish on Pypi
      if: startsWith(github.ref, 'refs/tags/')
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload --skip-existing dist/*.whl
